version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: ${POSTGRES_CONTAINER_NAME}
    restart: always
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_LOCAL_PORT}:${POSTGRES_DOCKER_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    platform: linux/amd64

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: safechain-backend
    env_file:
      - ./.env
      - ./backend/.env
    ports:
      - "${BACKEND_LOCAL_PORT}:${BACKEND_DOCKER_PORT}"
    depends_on:
      - postgres
    command: >
      sh -c "sleep 10 && bunx prisma generate && bunx prisma migrate deploy && bun run dev"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: safechain-frontend
    env_file:
      - ./.env
      - ./frontend/.env
    ports:
      - "${FRONTEND_LOCAL_PORT}:${FRONTEND_DOCKER_PORT}"
    depends_on:
      - backend

volumes:
  postgres_data: